### PR TITLE
Merge csv route checking to live

### PR DESCRIPTION
**Pull request by dalepotter**

### CODE REVIEW

**Comment by dalepotter** [comment]
Fair point on adding tests - we can add this to the weekly maintenance jobs backlog, or @andylolz is welcome to add if there is time...  Basing some new tests from [existing tests for response codes](https://github.com/IATI/IATI-Datastore/blob/c9772137ef120dd99210f3bbc60b08dc909f13d3/iati_datastore/iatilib/test/test_api.py#L223-L226) should do the trick.

Searching the code for how `DataStoreCSVView` is used also confused me too. However, this is deployed and working on the dev server though (running the `master` branch) - the previously functional query http://dev.datastore.iatistandard.org/api/1/access/budgettt.Hey_look.A_custom_filename.csv now returns a 404, as expected.

**Comment by andylolz** [comment]
Good point re. tests – Happy to add.

Not sure I follow re. the `format` parameter… This is Flask Magic™ in the form of [URL Route Registrations](http://flask.pocoo.org/docs/0.12/api/#url-route-registrations), i.e. `format` comes from e.g.:
https://github.com/IATI/IATI-Datastore/blob/199d9dd3/iati_datastore/iatilib/frontend/api1.py#L306

**Comment by andylolz** [comment]
I’ve opened #263 now, which adds a test that previously failed and now (with this fix) passes.

**Comment by andylolz** [comment]
@hayfield ping – I’ve added those tests… Does it look okay?

**Comment by hayfield** [comment]
The tests do indeed look OK.

(sorry about the delay - the relevant notifications must have been lost when catching up after a week off!)

**Pull request merged**
