### PR TITLE
Coverage should only include iati_datastore

### PR DESCRIPTION
**Pull request by andylolz**
This excludes dependencies from coverage tests.

It also excludes all test files.

### CODE REVIEW

**Comment by andylolz** [comment]
It’s worth running:

```bash
$ nosetests iati_datastore --with-coverage
$ coverage html
```

…and taking a look at coverage in more detail.

**Comment by andylolz** [comment]
Current output of `coverage report` on this branch:
```
$ coverage report
Name                                                       Stmts   Miss  Cover
------------------------------------------------------------------------------
iati_datastore/iatilib/__init__                               16      8    50%
iati_datastore/iatilib/codelists/__init__                     34      2    94%
iati_datastore/iatilib/codelists/enum                         63      9    86%
iati_datastore/iatilib/console                                55     55     0%
iati_datastore/iatilib/crawler                               286    105    63%
iati_datastore/iatilib/frontend/__init__                      30      9    70%
iati_datastore/iatilib/frontend/api1                         159     45    72%
iati_datastore/iatilib/frontend/dsfilter                      99     11    89%
iati_datastore/iatilib/frontend/serialize/__init__            11      0   100%
iati_datastore/iatilib/frontend/serialize/csv                198      7    96%
iati_datastore/iatilib/frontend/serialize/jsonserializer      58     15    74%
iati_datastore/iatilib/frontend/validators                    22      0   100%
iati_datastore/iatilib/loghandlers                            21      1    95%
iati_datastore/iatilib/model                                 243     10    96%
iati_datastore/iatilib/parse                                 319     44    86%
iati_datastore/iatilib/queue                                  31     20    35%
iati_datastore/iatilib/wsgi                                    7      7     0%
iati_datastore/setup                                           4      4     0%
------------------------------------------------------------------------------
TOTAL                                                       1656    352    79%
```

**Comment by andylolz** [comment]
This just adds a dotfile. I don’t think it should have the “waiting for dev datastore” label. It seems like it could be merged in advance of that.

**Comment by dalepotter** [comment]
Looks good, as code in the `alembic` folder is not used in the `iati_datastore`.

**Comment by andylolz** [comment]
Great – thanks!

**Pull request merged**
