### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nosvalds**
Adding a note that this is not the current live datastore and directing folks to the live one.

### CODE REVIEW

**Comment by andylolz** [comment]
> is not currently hosted live or maintained by IATI

That’s not my understanding… According to [this post on discuss](https://discuss.iatistandard.org/t/iatis-datastore-and-validator-tools-launched/2021/1):

> **Old Datastore API:** Between now and 22 March 2021 users can choose to either use existing API calls to return data from the old Datastore, or use a Redirect version from the Old Datastore to the new Datastore. Redirects can be tested by replacing “[datastore.iatistandard.org](http://datastore.iatistandard.org/)” in previous queries with “[datastoreredirect.iatistandard.org](http://datastoreredirect.iatistandard.org/).” By using this version, existing API calls will be redirected and return data from the new Datastore. After 22 March 2021, the old Datastore will be deprecated and **all** queries to the Old Datastore will automatically be redirected to corresponding queries on the new Datastore.

Also worth noting that the old datastore is currently down. See e.g.
http://datastore.iatistandard.org/api/1/about

**Comment by akmiller01** [comment]
> Also worth noting that the old datastore is currently down. See e.g.
> http://datastore.iatistandard.org/api/1/about

Cheers, Andy. Gave it a reboot and it's back up now.

**Comment by andylolz** [comment]
Thanks!

**Comment by andylolz** [comment]
Great – Thanks.

I don’t know if you have monitoring set up already, but https://status.codeforiati.org/ runs daily checks.

**Comment by nosvalds** [comment]
Thanks a lot @andylolz and @akmiller01 I was quite mistaken!

Fixed this right up.

**Review by akmiller01 — APPROVED** [review]

**Pull request merged**
